# Generated by Django 4.0.6 on 2022-07-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingslot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=70)),
                ('license_plate', models.CharField(max_length=8)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingslot.parkingslot')),
            ],
        ),
    ]
