# Generated by Django 3.1.4 on 2022-07-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingslot', '0002_carmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car',
            new_name='parking_slot',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='car',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
